version: '2'
services:
  web:
    image: "sellsoftware:v3.0"
    container_name: "compose-sellsoftware"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: "mysql:latest"
    container_name: "compose-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: 'testuser'
      MYSQL_PASS: '123456'
    ports:
      - "3306:3306"