version: '2'
services:
  web:
    image: "sellsoftware:v2.0"
    container_name: "compose-sellsoftware"
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: "mysql:latest"
    container_name: "compose-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: 'root'
      MYSQL_PASS: '123456'
    restart: always
    volumes:
      - "./db:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"
      - "./init:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"